---
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Rozumbunch\Documentationhub\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  Rozumbunch\Documentationhub\Service\MarkdownUtility:
    public: true

  Rozumbunch\Documentationhub\Service\DocumentationhubService:
    arguments:
      $markdownUtility: '@Rozumbunch\Documentationhub\Service\MarkdownUtility'

  Rozumbunch\Documentationhub\Service\PdfExportService:
    arguments:
      $documentationhubService: '@Rozumbunch\Documentationhub\Service\DocumentationhubService'
